version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      -"8000:8000"
    volumes:
      -./backend:/app

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      -"4200:80"
    depends_on:
      - backend